/*
 Generated by typeshare 1.13.3
*/

export type IpcToFrontend = 
	| { type: "None", data: number };

export type IpcToHost = 
	| { type: "None", data: number }
	| { type: "GetWorkspaceString", data?: undefined };

